export interface MediaItem {
    id: number;
    src: string;
    alt: string;
    category: 'Fashion' | 'Lifestyle' | 'Portrait' | 'Wedding';
    title: string;
    description: string;
    type: 'image' | 'video';
    thumbnail?: string;
}

export const allItems: MediaItem[] = [
    // ==================== WEDDING (22 images) ====================
    {
        id: 1,
        src: '/images/wed/DSC_9212.jpg',
        alt: 'Wedding Ceremony',
        category: 'Wedding',
        title: 'Sacred Vows',
        description: 'Capturing the beautiful moment of commitment.',
        type: 'image',
    },
    {
        id: 2,
        src: '/images/wed/DSC_9242.jpg',
        alt: 'Wedding Celebration',
        category: 'Wedding',
        title: 'Joyful Celebration',
        description: 'The happiness of two families coming together.',
        type: 'image',
    },
    {
        id: 3,
        src: '/images/wed/DSC_9266.jpg',
        alt: 'Wedding Couple',
        category: 'Wedding',
        title: 'Eternal Love',
        description: 'A timeless portrait of the newlyweds.',
        type: 'image',
    },
    {
        id: 4,
        src: '/images/wed/IMG_8321 copy.jpg',
        alt: 'Wedding Details',
        category: 'Wedding',
        title: 'Perfect Details',
        description: 'Every detail tells a story.',
        type: 'image',
    },
    {
        id: 5,
        src: '/images/wed/IMG_9847.jpg',
        alt: 'Wedding Reception',
        category: 'Wedding',
        title: 'Grand Reception',
        description: 'Celebrating love with family and friends.',
        type: 'image',
    },
    {
        id: 6,
        src: '/images/wed/JAH_5768.jpg',
        alt: 'Wedding Moments',
        category: 'Wedding',
        title: 'Precious Moments',
        description: 'Candid moments of pure joy.',
        type: 'image',
    },
    {
        id: 7,
        src: '/images/wed/opulence.jpg',
        alt: 'Luxury Wedding',
        category: 'Wedding',
        title: 'Opulent Affair',
        description: 'Elegance and sophistication.',
        type: 'image',
    },
    {
        id: 8,
        src: '/images/wed/valentine8.jpg',
        alt: 'Romantic Wedding',
        category: 'Wedding',
        title: 'Romance in the Air',
        description: 'Love captured in every frame.',
        type: 'image',
    },
    {
        id: 9,
        src: '/images/wed/DSC_0201 copy.jpg',
        alt: 'Wedding Portrait',
        category: 'Wedding',
        title: 'Elegant Portrait',
        description: 'A stunning bridal portrait.',
        type: 'image',
    },
    {
        id: 10,
        src: '/images/wed/IMG_2500.jpg',
        alt: 'Wedding Day',
        category: 'Wedding',
        title: 'The Big Day',
        description: 'Capturing the essence of the celebration.',
        type: 'image',
    },
    {
        id: 11,
        src: '/images/wed/IMG_8366 copy.jpg',
        alt: 'Wedding Ceremony Moment',
        category: 'Wedding',
        title: 'Ceremony Highlights',
        description: 'The most sacred moments documented.',
        type: 'image',
    },
    {
        id: 12,
        src: '/images/wed/IMG_8405 copy.jpg',
        alt: 'Wedding Celebration',
        category: 'Wedding',
        title: 'Pure Happiness',
        description: 'Joy radiating through every moment.',
        type: 'image',
    },
    {
        id: 13,
        src: '/images/wed/IMG_9849.jpg',
        alt: 'Wedding Reception',
        category: 'Wedding',
        title: 'Reception Elegance',
        description: 'Sophisticated celebration captured beautifully.',
        type: 'image',
    },
    {
        id: 14,
        src: '/images/wed/IMG_9886.jpg',
        alt: 'Wedding Dance',
        category: 'Wedding',
        title: 'First Dance',
        description: 'A moment to remember forever.',
        type: 'image',
    },
    {
        id: 15,
        src: '/images/wed/JAH_5779.jpg',
        alt: 'Wedding Traditions',
        category: 'Wedding',
        title: 'Cultural Heritage',
        description: 'Honoring beautiful traditions.',
        type: 'image',
    },
    {
        id: 16,
        src: '/images/wed/JAH_5789.jpg',
        alt: 'Wedding Family',
        category: 'Wedding',
        title: 'Family Unity',
        description: 'Two families becoming one.',
        type: 'image',
    },
    {
        id: 17,
        src: '/images/wed/JAH_5806.jpg',
        alt: 'Wedding Ceremony',
        category: 'Wedding',
        title: 'Sacred Union',
        description: 'The moment of eternal commitment.',
        type: 'image',
    },
    {
        id: 18,
        src: '/images/wed/JAH_5893.jpg',
        alt: 'Wedding Celebration',
        category: 'Wedding',
        title: 'Celebration of Love',
        description: 'Joy and laughter throughout the day.',
        type: 'image',
    },
    {
        id: 19,
        src: '/images/wed/JAH_5902.jpg',
        alt: 'Wedding Couple Portrait',
        category: 'Wedding',
        title: 'Newlywed Bliss',
        description: 'The beginning of forever.',
        type: 'image',
    },
    {
        id: 20,
        src: '/images/wed/_MG_0132.jpg',
        alt: 'Wedding Photography',
        category: 'Wedding',
        title: 'Artistic Vision',
        description: 'Creative wedding photography at its finest.',
        type: 'image',
    },
    {
        id: 21,
        src: '/images/wed/opulence.jpg1.jpg',
        alt: 'Luxury Wedding Details',
        category: 'Wedding',
        title: 'Luxury Details',
        description: 'Exquisite attention to every detail.',
        type: 'image',
    },
    {
        id: 22,
        src: '/images/wed/val2.jpg',
        alt: 'Wedding Love Story',
        category: 'Wedding',
        title: 'Love Story',
        description: 'A beautiful journey captured in time.',
        type: 'image',
    },

    // ==================== PORTRAIT (33 images) ====================
    {
        id: 23,
        src: '/images/portrait/JADE.jpg',
        alt: 'Portrait Session',
        category: 'Portrait',
        title: 'Jade',
        description: 'A stunning portrait session.',
        type: 'image',
    },
    {
        id: 24,
        src: '/images/portrait/mide.jpg',
        alt: 'Professional Portrait',
        category: 'Portrait',
        title: 'Professional Elegance',
        description: 'Capturing confidence and style.',
        type: 'image',
    },
    {
        id: 25,
        src: '/images/portrait/IMG_9176.jpg',
        alt: 'Creative Portrait',
        category: 'Portrait',
        title: 'Creative Expression',
        description: 'Artistic portrait photography.',
        type: 'image',
    },
    {
        id: 26,
        src: '/images/portrait/DSC_0107.jpg',
        alt: 'Studio Portrait',
        category: 'Portrait',
        title: 'Studio Session',
        description: 'Professional studio photography.',
        type: 'image',
    },
    {
        id: 27,
        src: '/images/portrait/IMG_9375.jpg',
        alt: 'Outdoor Portrait',
        category: 'Portrait',
        title: 'Natural Light',
        description: 'Beautiful outdoor portrait.',
        type: 'image',
    },
    {
        id: 28,
        src: '/images/portrait/portrait-maestros.jpg',
        alt: 'Portrait Maestro',
        category: 'Portrait',
        title: 'Portrait Maestro',
        description: 'Mastery in portrait photography.',
        type: 'image',
    },
    {
        id: 29,
        src: '/images/portrait/MNYL7553.jpg',
        alt: 'Elegant Portrait',
        category: 'Portrait',
        title: 'Timeless Elegance',
        description: 'Classic portrait photography.',
        type: 'image',
    },
    {
        id: 30,
        src: '/images/portrait/IMG_4537.jpg',
        alt: 'Character Portrait',
        category: 'Portrait',
        title: 'Character Study',
        description: 'Capturing personality and character.',
        type: 'image',
    },
    {
        id: 31,
        src: '/images/portrait/2.jpg',
        alt: 'Contemporary Portrait',
        category: 'Portrait',
        title: 'Contemporary Style',
        description: 'Modern portrait photography.',
        type: 'image',
    },
    {
        id: 32,
        src: '/images/portrait/43.jpg',
        alt: 'Artistic Portrait',
        category: 'Portrait',
        title: 'Artistic Vision',
        description: 'Creative and artistic approach.',
        type: 'image',
    },
    {
        id: 33,
        src: '/images/portrait/DSC_0031.jpg',
        alt: 'Professional Headshot',
        category: 'Portrait',
        title: 'Professional Headshot',
        description: 'Perfect for business and branding.',
        type: 'image',
    },
    {
        id: 34,
        src: '/images/portrait/DSC_0033.jpg',
        alt: 'Portrait Photography',
        category: 'Portrait',
        title: 'Confident Presence',
        description: 'Showcasing strength and confidence.',
        type: 'image',
    },
    {
        id: 35,
        src: '/images/portrait/DSC_0041.jpg',
        alt: 'Studio Portrait Session',
        category: 'Portrait',
        title: 'Studio Excellence',
        description: 'Premium studio portrait work.',
        type: 'image',
    },
    {
        id: 36,
        src: '/images/portrait/DSC_0059.jpg',
        alt: 'Dramatic Portrait',
        category: 'Portrait',
        title: 'Dramatic Lighting',
        description: 'Playing with light and shadow.',
        type: 'image',
    },
    {
        id: 37,
        src: '/images/portrait/DSC_0117.jpg',
        alt: 'Personal Branding',
        category: 'Portrait',
        title: 'Personal Branding',
        description: 'Building your visual identity.',
        type: 'image',
    },
    {
        id: 38,
        src: '/images/portrait/DSC_0126.jpg',
        alt: 'Professional Portrait',
        category: 'Portrait',
        title: 'Professional Edge',
        description: 'Sharp, professional imagery.',
        type: 'image',
    },
    {
        id: 39,
        src: '/images/portrait/DSC_0544.jpg2.jpg',
        alt: 'Creative Portrait',
        category: 'Portrait',
        title: 'Creative Approach',
        description: 'Unique and creative perspective.',
        type: 'image',
    },
    {
        id: 40,
        src: '/images/portrait/IMG_4236.jpg',
        alt: 'Portrait Session',
        category: 'Portrait',
        title: 'Natural Beauty',
        description: 'Capturing authentic beauty.',
        type: 'image',
    },
    {
        id: 41,
        src: '/images/portrait/IMG_4741.jpg',
        alt: 'Lifestyle Portrait',
        category: 'Portrait',
        title: 'Lifestyle Blend',
        description: 'Where portrait meets lifestyle.',
        type: 'image',
    },
    {
        id: 42,
        src: '/images/portrait/IMG_9069.jpg',
        alt: 'Portrait Photography',
        category: 'Portrait',
        title: 'Genuine Moments',
        description: 'Authentic and genuine expressions.',
        type: 'image',
    },
    {
        id: 43,
        src: '/images/portrait/IMG_9077.jpg',
        alt: 'Professional Portrait',
        category: 'Portrait',
        title: 'Professional Grace',
        description: 'Elegance in every frame.',
        type: 'image',
    },
    {
        id: 44,
        src: '/images/portrait/IMG_9127.jpg',
        alt: 'Portrait Session',
        category: 'Portrait',
        title: 'Refined Portraits',
        description: 'Sophisticated portrait work.',
        type: 'image',
    },
    {
        id: 45,
        src: '/images/portrait/IMG_9179.jpg',
        alt: 'Contemporary Portrait',
        category: 'Portrait',
        title: 'Contemporary Look',
        description: 'Fresh and modern approach.',
        type: 'image',
    },
    {
        id: 46,
        src: '/images/portrait/IMG_9356.jpg',
        alt: 'Artistic Portrait',
        category: 'Portrait',
        title: 'Artistic Excellence',
        description: 'Art meets photography.',
        type: 'image',
    },
    {
        id: 47,
        src: '/images/portrait/IMG_9385.jpg',
        alt: 'Portrait Photography',
        category: 'Portrait',
        title: 'Signature Style',
        description: 'Distinctive portrait photography.',
        type: 'image',
    },
    {
        id: 48,
        src: '/images/portrait/Jade-and-Olamide1.jpg',
        alt: 'Duo Portrait',
        category: 'Portrait',
        title: 'Jade & Olamide',
        description: 'Capturing connection between people.',
        type: 'image',
    },
    {
        id: 49,
        src: '/images/portrait/MNYL4417.jpg',
        alt: 'Professional Portrait',
        category: 'Portrait',
        title: 'Executive Portrait',
        description: 'High-end professional photography.',
        type: 'image',
    },
    {
        id: 50,
        src: '/images/portrait/MNYL4454.jpg',
        alt: 'Portrait Session',
        category: 'Portrait',
        title: 'Premium Portraits',
        description: 'Luxury portrait photography.',
        type: 'image',
    },
    {
        id: 51,
        src: '/images/portrait/MNYL7578.jpg',
        alt: 'Studio Portrait',
        category: 'Portrait',
        title: 'Studio Mastery',
        description: 'Expert studio work.',
        type: 'image',
    },
    {
        id: 52,
        src: '/images/portrait/lifestyle.jpg',
        alt: 'Lifestyle Portrait',
        category: 'Portrait',
        title: 'Lifestyle Portrait',
        description: 'Natural and candid moments.',
        type: 'image',
    },
    {
        id: 53,
        src: '/images/portrait/mide-4.jpg',
        alt: 'Portrait Session Mide',
        category: 'Portrait',
        title: 'Mide Series',
        description: 'Beautiful portrait series.',
        type: 'image',
    },
    {
        id: 54,
        src: '/images/portrait/mide2.jpg',
        alt: 'Mide Portrait 2',
        category: 'Portrait',
        title: 'Elegant Mide',
        description: 'Elegant and sophisticated.',
        type: 'image',
    },
    {
        id: 55,
        src: '/images/portrait/mide5.jpg',
        alt: 'Mide Portrait 5',
        category: 'Portrait',
        title: 'Mide Collection',
        description: 'Complete portrait collection.',
        type: 'image',
    },
    {
        id: 56,
        src: '/images/portrait/okejacobs..jpg',
        alt: 'TheOkeJacobs Portrait',
        category: 'Portrait',
        title: 'Signature Work',
        description: 'TheOkeJacobs signature style.',
        type: 'image',
    },

    // ==================== LIFESTYLE (10 images) ====================
    {
        id: 57,
        src: '/images/lifestyle/kiki2.jpg',
        alt: 'Lifestyle Shoot',
        category: 'Lifestyle',
        title: 'Lifestyle Moments',
        description: 'Authentic lifestyle photography.',
        type: 'image',
    },
    {
        id: 58,
        src: '/images/lifestyle/IMG_9469-Recovered.jpg',
        alt: 'Candid Lifestyle',
        category: 'Lifestyle',
        title: 'Candid Moments',
        description: 'Natural and spontaneous.',
        type: 'image',
    },
    {
        id: 59,
        src: '/images/lifestyle/magazine1.jpg',
        alt: 'Editorial Lifestyle',
        category: 'Lifestyle',
        title: 'Editorial Style',
        description: 'Magazine-worthy lifestyle shots.',
        type: 'image',
    },
    {
        id: 60,
        src: '/images/lifestyle/mutiple.jpg',
        alt: 'Group Lifestyle',
        category: 'Lifestyle',
        title: 'Together',
        description: 'Capturing connections and relationships.',
        type: 'image',
    },
    {
        id: 61,
        src: '/images/lifestyle/IMG_9556.jpg',
        alt: 'Urban Lifestyle',
        category: 'Lifestyle',
        title: 'Urban Life',
        description: 'City lifestyle photography.',
        type: 'image',
    },
    {
        id: 62,
        src: '/images/lifestyle/2.jpg',
        alt: 'Lifestyle Portrait',
        category: 'Lifestyle',
        title: 'Lifestyle Portrait',
        description: 'Blending portrait and lifestyle.',
        type: 'image',
    },
    {
        id: 63,
        src: '/images/lifestyle/DSC_0015112.jpg',
        alt: 'Lifestyle Session',
        category: 'Lifestyle',
        title: 'Natural Living',
        description: 'Capturing everyday beauty.',
        type: 'image',
    },
    {
        id: 64,
        src: '/images/lifestyle/IMG_9488.jpg',
        alt: 'Lifestyle Photography',
        category: 'Lifestyle',
        title: 'Authentic Life',
        description: 'Real moments, real emotions.',
        type: 'image',
    },
    {
        id: 65,
        src: '/images/lifestyle/kikiiii.jpg',
        alt: 'Lifestyle Shoot Kiki',
        category: 'Lifestyle',
        title: 'Kiki Lifestyle',
        description: 'Lifestyle photography series.',
        type: 'image',
    },
    {
        id: 66,
        src: '/images/lifestyle/okikiii.jpg',
        alt: 'Lifestyle Session',
        category: 'Lifestyle',
        title: 'Daily Moments',
        description: 'Finding beauty in the everyday.',
        type: 'image',
    },

    // ==================== FASHION (6 images) ====================
    {
        id: 67,
        src: '/images/fashion/DSC_0011.jpg',
        alt: 'Fashion Editorial',
        category: 'Fashion',
        title: 'Fashion Forward',
        description: 'High-fashion editorial photography.',
        type: 'image',
    },
    {
        id: 68,
        src: '/images/fashion/DSC_0036.jpg11.jpg',
        alt: 'Fashion Shoot',
        category: 'Fashion',
        title: 'Style Statement',
        description: 'Bold fashion photography.',
        type: 'image',
    },
    {
        id: 69,
        src: '/images/fashion/DSC_0073.jpg',
        alt: 'Fashion Model',
        category: 'Fashion',
        title: 'Model Portfolio',
        description: 'Professional fashion modeling.',
        type: 'image',
    },
    {
        id: 70,
        src: '/images/fashion/DSC_0077.jpg',
        alt: 'Fashion Photography',
        category: 'Fashion',
        title: 'Haute Couture',
        description: 'Elegant fashion photography.',
        type: 'image',
    },
    {
        id: 71,
        src: '/images/fashion/DSC_0082.jpg',
        alt: 'Fashion Portrait',
        category: 'Fashion',
        title: 'Fashion Portrait',
        description: 'Stylish and sophisticated.',
        type: 'image',
    },
    {
        id: 72,
        src: '/images/fashion/DSC_0004.jpg',
        alt: 'Fashion Art',
        category: 'Fashion',
        title: 'Artistic Fashion',
        description: 'Where fashion meets art.',
        type: 'image',
    },
];

// Helper functions for filtering and organizing
export const getItemsByCategory = (category: string): MediaItem[] => {
    if (category === 'All') return allItems;
    return allItems.filter(item => item.category === category);
};

export const getCategoryCounts = () => {
    return {
        All: allItems.length,
        Wedding: allItems.filter(item => item.category === 'Wedding').length,
        Portrait: allItems.filter(item => item.category === 'Portrait').length,
        Lifestyle: allItems.filter(item => item.category === 'Lifestyle').length,
        Fashion: allItems.filter(item => item.category === 'Fashion').length,
    };
};

export const categories = ['All', 'Wedding', 'Portrait', 'Lifestyle', 'Fashion'] as const;
// Generate more unique items if needed
export const generateMoreItems = (startId: number, count: number): MediaItem[] => {
    const categories = ['Wedding', 'Portrait', 'Lifestyle', 'Fashion'];
    const newItems: MediaItem[] = [];

    for (let i = 0; i < count; i++) {
        const baseItem = allItems[i % allItems.length];
        newItems.push({
            ...baseItem,
            id: startId + i,
            // Don't duplicate - fetch from a different source or mark as placeholder
        });
    }

    return newItems;
};